[tool.robotpy-build]
base_package = "wpinet"

[tool.robotpy-build.wrappers."wpinet"]
name = "wpinet"
sources = [
    "wpinet/src/main.cpp",
]

depends = ["wpiutil"]
generation_data = "gen"

[tool.robotpy-build.wrappers."wpinet".maven_lib_download]
artifact_id = "wpinet-cpp"
group_id = "edu.wpi.first.wpinet"
# repo_url = "https://frcmaven.wpi.edu/artifactory/release"
repo_url = "https://frcmaven.wpi.edu/artifactory/development"
version = "2023.1.1-beta-7-32-gc11bd27"

libs = ["wpinet"]

[tool.robotpy-build.wrappers."wpinet".autogen_headers]
# wpinet
PortForwarder = "wpinet/PortForwarder.h"

[tool.robotpy-build.metadata]
name = "robotpy-wpinet"
description = "Binary wrapper for FRC wpinet library"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-wpinet"
license = "BSD-3-Clause"
install_requires = [
    "robotpy-wpiutil<2024.0.0,>=2023.0.0b7",
]

[build-system]
requires = [
    "robotpy-build<2024.0.0,>=2023.0.0b16",
    "robotpy-wpiutil<2024.0.0,>=2023.0.0b7",
]
